CREATE DATABASE TesteTecnicoImobiliaria;
GO
USE TesteTecnicoImobiliaria;
GO

IF OBJECT_ID('dbo.CLIENTE', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.CLIENTE
    (
        CD_CLIENTE   INT IDENTITY(1,1) PRIMARY KEY,
        NM_CLIENTE   VARCHAR(150) NOT NULL,
        DS_EMAIL     VARCHAR(150) NOT NULL,
        NR_CPF       VARCHAR(11)  NULL,
        NR_CNPJ      VARCHAR(14)  NULL,
        FL_ATIVO     BIT          NOT NULL DEFAULT 1
    );
END;
GO

IF OBJECT_ID('dbo.TIPO_IMOVEL', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.TIPO_IMOVEL
    (
        CD_TIPO_IMOVEL INT IDENTITY(1,1) PRIMARY KEY,
        DS_TIPO_IMOVEL VARCHAR(100) NOT NULL
    );

    INSERT INTO dbo.TIPO_IMOVEL (DS_TIPO_IMOVEL)
    VALUES ('Venda'), ('Aluguel');
END;
GO

IF OBJECT_ID('dbo.IMOVEL', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.IMOVEL
    (
        CD_IMOVEL      INT IDENTITY(1,1) PRIMARY KEY,
        CD_CLIENTE     INT NOT NULL,
        CD_TIPO_IMOVEL INT NOT NULL,
        VL_IMOVEL      DECIMAL(18,2) NOT NULL,
        DT_PUBLICACAO  DATE NOT NULL,
        DS_IMOVEL      VARCHAR(MAX) NULL,
        FL_ATIVO       BIT NOT NULL DEFAULT 1,
        NR_CEP         VARCHAR(8) NULL,
        NM_LOGRADOURO  VARCHAR(150) NULL,
        DS_COMPLEMENTO VARCHAR(100) NULL,
        NM_BAIRRO      VARCHAR(100) NULL,
        NM_LOCALIDADE  VARCHAR(100) NULL,
        SG_UF          CHAR(2) NULL,
        CONSTRAINT FK_IMOVEL_CLIENTE FOREIGN KEY (CD_CLIENTE) REFERENCES dbo.CLIENTE (CD_CLIENTE),
        CONSTRAINT FK_IMOVEL_TIPO FOREIGN KEY (CD_TIPO_IMOVEL) REFERENCES dbo.TIPO_IMOVEL (CD_TIPO_IMOVEL)
    );
END;
GO
